// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQH9t_Pa5ZNagQRMZwLx__pMMRw7Uy3QQ',
    appId: '1:47164634245:web:0a7a74ceb3b6c9bef0a5ec',
    messagingSenderId: '47164634245',
    projectId: 'flutterapp1-f6df9',
    authDomain: 'flutterapp1-f6df9.firebaseapp.com',
    storageBucket: 'flutterapp1-f6df9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3rJOBmVLM8qpwC8utP8fCV0gwoUInx5o',
    appId: '1:47164634245:android:6ec399ad0b0b3281f0a5ec',
    messagingSenderId: '47164634245',
    projectId: 'flutterapp1-f6df9',
    storageBucket: 'flutterapp1-f6df9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKpLlr39KTCArnhuKy1-HRQkNTawbd0Jw',
    appId: '1:47164634245:ios:ee08abe015acf44ff0a5ec',
    messagingSenderId: '47164634245',
    projectId: 'flutterapp1-f6df9',
    storageBucket: 'flutterapp1-f6df9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKpLlr39KTCArnhuKy1-HRQkNTawbd0Jw',
    appId: '1:47164634245:ios:ee08abe015acf44ff0a5ec',
    messagingSenderId: '47164634245',
    projectId: 'flutterapp1-f6df9',
    storageBucket: 'flutterapp1-f6df9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQH9t_Pa5ZNagQRMZwLx__pMMRw7Uy3QQ',
    appId: '1:47164634245:web:2e65ebb3fed01a87f0a5ec',
    messagingSenderId: '47164634245',
    projectId: 'flutterapp1-f6df9',
    authDomain: 'flutterapp1-f6df9.firebaseapp.com',
    storageBucket: 'flutterapp1-f6df9.firebasestorage.app',
  );
}
